apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx-rollout
  namespace: argocd
spec:
  replicas: 3
  strategy:
    canary:
      steps:
        - setWeight: 50
        - pause: {duration: 30s}
        - setWeight: 100
        - pause: {duration: 30s}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
